CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(20),
    direccion VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS usuarios_login (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL DEFAULT 'cliente',
    id_cliente INT,
    FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
);

CREATE TABLE IF NOT EXISTS marca (
    id_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS proveedores (
    id_proveedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS productos (
    id_producto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(255) NOT NULL,
    precio_venta DECIMAL(18,2) NOT NULL,
    costo DECIMAL(18,2) DEFAULT 0,
    id_marca INT,
    id_proveedor INT,
    imagen_url VARCHAR(500),
    categoria VARCHAR(100) DEFAULT 'General',
    id_vendedor INT,
    condicion_uso VARCHAR(50) DEFAULT 'Nuevo',
    detalles_producto VARCHAR(500),
    FOREIGN KEY (id_marca) REFERENCES marca(id_marca),
    FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor),
    FOREIGN KEY (id_vendedor) REFERENCES clientes(id_cliente)
);

CREATE TABLE IF NOT EXISTS orden_venta (
    id_orden INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT,
    fecha_orden DATETIME NOT NULL,
    status_orden VARCHAR(50) DEFAULT 'Procesando Pago',
    total_orden DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
);

CREATE TABLE IF NOT EXISTS detalle_orden (
    id_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden INT NOT NULL,
    id_producto INT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario DECIMAL(18,2) NOT NULL,
    subtotal DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (id_orden) REFERENCES orden_venta(id_orden),
    FOREIGN KEY (id_producto) REFERENCES productos(id_producto)
);
